### ISSUE TITLE
Crash if I execute an example.

### ISSUE THREAD

**Issue by matrixise** [benoitc/offset#2]
If I execute this code, I get an error.

``` python
#!/usr/bin/env python
from __future__ import print_function

from offset import *
from offset import time
from offset import syscall

def test():
    print("ok")

def test_syscall():
    go(tesT)
    print(syscall.getcwd())

@maintask
def main():
    go(test_syscall)
    print("start")

run()
```

```
Traceback (most recent call last):
  File "/tmp/offset/examples/goroutine_syscall.py", line 6, in <module>
    from offset import syscall
  File "/Users/stephane/src/projects/externals/offset/offset/syscall.py", line 45, in <module>
    _bootstrap()
  File "/Users/stephane/src/projects/externals/offset/offset/syscall.py", line 38, in _bootstrap
    f = syscall(obj)
  File "/Users/stephane/src/projects/externals/offset/offset/syscall.py", line 21, in syscall
    @functools.wraps(func)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'functools.partial' object has no attribute '__module__'
```

Voila,

**Comment by benoitc** [comment]
btw you have a typo in test_syscall. It should be test and not tesT

**Comment by matrixise** [comment]
yes :/
